# Generated by Django 6.0.1 on 2026-01-07 15:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssemblyBenchEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "ASSEMBLY_BENCH",
            },
        ),
        migrations.CreateModel(
            name="CampaignDocumentTypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "CAMPAIGN_DOCUMENT_TYPES",
            },
        ),
        migrations.CreateModel(
            name="CampaignEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("semester", models.CharField(max_length=2)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("dtri_number", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
            ],
            options={
                "db_table": "CAMPAIGN",
            },
        ),
        migrations.CreateModel(
            name="CampaignInstallationsEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "CAMPAIGN_INSTALLATIONS",
            },
        ),
        migrations.CreateModel(
            name="CampaignRolesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "CAMPAIGN_ROLES",
            },
        ),
        migrations.CreateModel(
            name="CampaignStatusEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "CAMPAIGN_STATUS",
            },
        ),
        migrations.CreateModel(
            name="CampaignTypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "CAMPAIGN_TYPES",
            },
        ),
        migrations.CreateModel(
            name="FsecCategoryEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "FSEC_CATEGORY",
            },
        ),
        migrations.CreateModel(
            name="FsecDocumentTypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "FSEC_DOCUMENT_TYPES",
            },
        ),
        migrations.CreateModel(
            name="FsecRackEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
                ("is_full", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "FSEC_RACK",
            },
        ),
        migrations.CreateModel(
            name="FsecRolesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "FSEC_ROLES",
            },
        ),
        migrations.CreateModel(
            name="FsecStatusEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "FSEC_STATUS",
            },
        ),
        migrations.CreateModel(
            name="MetrologyMachineEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "METROLOGY_MACHINE",
            },
        ),
        migrations.CreateModel(
            name="CampaignDocumentSubtypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                (
                    "type_id",
                    models.ForeignKey(
                        db_column="type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="app.campaigndocumenttypesentity",
                    ),
                ),
            ],
            options={
                "db_table": "CAMPAIGN_DOCUMENT_SUBTYPES",
            },
        ),
        migrations.CreateModel(
            name="CampaignDocumentsEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("date", models.DateField()),
                (
                    "subtype_id",
                    models.ForeignKey(
                        db_column="subtype_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="app.campaigndocumentsubtypesentity",
                    ),
                ),
                (
                    "campaign_uuid",
                    models.ForeignKey(
                        db_column="campaign_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app.campaignentity",
                    ),
                ),
            ],
            options={
                "db_table": "CAMPAIGN_DOCUMENTS",
            },
        ),
        migrations.AddField(
            model_name="campaignentity",
            name="installation_id",
            field=models.ForeignKey(
                db_column="installation_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="app.campaigninstallationsentity",
            ),
        ),
        migrations.AddField(
            model_name="campaignentity",
            name="status_id",
            field=models.ForeignKey(
                db_column="status_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="app.campaignstatusentity",
            ),
        ),
        migrations.CreateModel(
            name="CampaignTeamsEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "campaign_uuid",
                    models.ForeignKey(
                        db_column="campaign_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="app.campaignentity",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_members",
                        to="app.campaignrolesentity",
                    ),
                ),
            ],
            options={
                "db_table": "CAMPAIGN_TEAMS",
            },
        ),
        migrations.AddField(
            model_name="campaignentity",
            name="type_id",
            field=models.ForeignKey(
                db_column="type_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="app.campaigntypesentity",
            ),
        ),
        migrations.CreateModel(
            name="FsecDocumentSubtypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                (
                    "type_id",
                    models.ForeignKey(
                        db_column="type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="app.fsecdocumenttypesentity",
                    ),
                ),
            ],
            options={
                "db_table": "FSEC_DOCUMENT_SUBTYPES",
            },
        ),
        migrations.CreateModel(
            name="FsecEntity",
            fields=[
                (
                    "version_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fsec_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True, max_length=4000, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("shooting_date", models.DateField(blank=True, null=True)),
                ("preshooting_pressure", models.FloatField(blank=True, null=True)),
                (
                    "experience_srxx",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("depressurization_failed", models.BooleanField(blank=True, null=True)),
                (
                    "campaign_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="campaign_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fsecs",
                        to="app.campaignentity",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fsecs",
                        to="app.fseccategoryentity",
                    ),
                ),
                (
                    "rack_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="rack_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fsecs",
                        to="app.fsecrackentity",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        db_column="status_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fsecs",
                        to="app.fsecstatusentity",
                    ),
                ),
            ],
            options={
                "db_table": "FSEC",
                "unique_together": {("campaign_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="FsecDocumentsEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("date", models.DateField()),
                (
                    "subtype_id",
                    models.ForeignKey(
                        db_column="subtype_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="app.fsecdocumentsubtypesentity",
                    ),
                ),
                (
                    "fsec_id",
                    models.ForeignKey(
                        db_column="fsec_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "FSEC_DOCUMENTS",
            },
        ),
        migrations.CreateModel(
            name="DepressurizationStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_fulfilment", models.DateField(blank=True, null=True)),
                ("pressure_gauge", models.FloatField(blank=True, null=True)),
                (
                    "enclosure_pressure_measured",
                    models.FloatField(blank=True, null=True),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "observations",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                (
                    "depressurization_time_before_firing",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "computed_pressure_before_firing",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depressurization_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "DEPRESSURIZATION_STEP",
            },
        ),
        migrations.CreateModel(
            name="AssemblyStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hydrometric_temperature", models.FloatField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "assembly_bench",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assembly_steps",
                        to="app.assemblybenchentity",
                    ),
                ),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "ASSEMBLY_STEP",
            },
        ),
        migrations.CreateModel(
            name="AirtightnessTestLpStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leak_rate_dtri",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gas_type", models.CharField(blank=True, max_length=200, null=True)),
                ("experiment_pressure", models.FloatField(blank=True, null=True)),
                (
                    "airtightness_test_duration",
                    models.FloatField(blank=True, null=True),
                ),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_fulfilment", models.DateField(blank=True, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airtightness_test_lp_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "AIRTIGHTNESS_TEST_LP_STEP",
            },
        ),
        migrations.CreateModel(
            name="FsecTeamsEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "fsec_id",
                    models.ForeignKey(
                        db_column="fsec_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="app.fsecentity",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_members",
                        to="app.fsecrolesentity",
                    ),
                ),
            ],
            options={
                "db_table": "FSEC_TEAMS",
            },
        ),
        migrations.CreateModel(
            name="GasFillingBpStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leak_rate_dtri",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gas_type", models.CharField(blank=True, max_length=200, null=True)),
                ("experiment_pressure", models.FloatField(blank=True, null=True)),
                ("leak_test_duration", models.FloatField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_fulfilment", models.DateField(blank=True, null=True)),
                ("gas_base", models.IntegerField(blank=True, null=True)),
                ("gas_container", models.IntegerField(blank=True, null=True)),
                (
                    "observations",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gas_filling_bp_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "GAS_FILLING_BP_STEP",
            },
        ),
        migrations.CreateModel(
            name="GasFillingHpStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leak_rate_dtri",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gas_type", models.CharField(blank=True, max_length=200, null=True)),
                ("experiment_pressure", models.FloatField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_fulfilment", models.DateField(blank=True, null=True)),
                ("gas_base", models.IntegerField(blank=True, null=True)),
                ("gas_container", models.IntegerField(blank=True, null=True)),
                (
                    "observations",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gas_filling_hp_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "GAS_FILLING_HP_STEP",
            },
        ),
        migrations.CreateModel(
            name="MetrologyStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrology_steps",
                        to="app.fsecentity",
                    ),
                ),
                (
                    "machine_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="machine_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metrology_steps",
                        to="app.metrologymachineentity",
                    ),
                ),
            ],
            options={
                "db_table": "METROLOGY_STEP",
            },
        ),
        migrations.CreateModel(
            name="PermeationStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gas_type", models.CharField(blank=True, max_length=200, null=True)),
                ("target_pressure", models.FloatField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_end_date", models.DateTimeField(blank=True, null=True)),
                ("sensor_pressure", models.FloatField(blank=True, null=True)),
                ("computed_shot_pressure", models.FloatField(blank=True, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permeation_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "PERMEATION_STEP",
            },
        ),
        migrations.CreateModel(
            name="PicturesStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "PICTURES_STEP",
            },
        ),
        migrations.CreateModel(
            name="RepressurizationStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operator", models.CharField(blank=True, max_length=200, null=True)),
                ("gas_type", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_end_date", models.DateTimeField(blank=True, null=True)),
                ("sensor_pressure", models.FloatField(blank=True, null=True)),
                ("computed_pressure", models.FloatField(blank=True, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repressurization_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "REPRESSURIZATION_STEP",
            },
        ),
        migrations.CreateModel(
            name="SealingStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interface_io",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("comments", models.TextField(blank=True, max_length=4000, null=True)),
                (
                    "fsec_version_id",
                    models.ForeignKey(
                        db_column="fsec_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sealing_steps",
                        to="app.fsecentity",
                    ),
                ),
            ],
            options={
                "db_table": "SEALING_STEP",
            },
        ),
        migrations.AlterUniqueTogether(
            name="campaignentity",
            unique_together={("name", "year", "semester")},
        ),
    ]
