# Generated by Django 6.0.1 on 2026-01-08 20:29

from django.db import migrations


def seed_campaign_roles(apps, schema_editor):
    """Insert initial campaign roles."""
    CampaignRolesEntity = apps.get_model("app", "CampaignRolesEntity")

    roles = [
        {"id": 0, "label": "MOE"},
        {"id": 1, "label": "RCE"},
        {"id": 2, "label": "IEC"},
    ]

    for role_data in roles:
        CampaignRolesEntity.objects.get_or_create(id=role_data["id"], defaults={"label": role_data["label"]})


def reverse_seed_campaign_roles(apps, schema_editor):
    """Remove seeded campaign roles."""
    CampaignRolesEntity = apps.get_model("app", "CampaignRolesEntity")
    CampaignRolesEntity.objects.filter(id__in=[0, 1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_campaign_roles, reverse_seed_campaign_roles),
    ]
