# Generated by Django 6.0.1 on 2026-01-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_seed_campaign_referential"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignFileTypesEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                (
                    "subtype_id",
                    models.ForeignKey(
                        db_column="subtype_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_types",
                        to="app.campaigndocumentsubtypesentity",
                    ),
                ),
            ],
            options={
                "db_table": "CAMPAIGN_FILE_TYPES",
            },
        ),
        migrations.AddField(
            model_name="campaigndocumentsentity",
            name="file_type_id",
            field=models.ForeignKey(
                blank=True,
                db_column="file_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="app.campaignfiletypesentity",
            ),
        ),
    ]
