# Generated by Django 6.0.1 on 2026-01-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_move_files_to_filetypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrologystepentity",
            name="metrologist_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="metrologystepentity",
            name="rack_id",
            field=models.ForeignKey(
                blank=True,
                db_column="rack_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metrology_steps",
                to="app.fsecrackentity",
            ),
        ),
    ]
