# Generated by Django 6.0.1 on 2026-01-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_add_rack_and_metrologist_to_metrology_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="sealingstepentity",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sealingstepentity",
            name="metrologist_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sealingstepentity",
            name="rack_id",
            field=models.ForeignKey(
                blank=True,
                db_column="rack_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sealing_steps",
                to="app.fsecrackentity",
            ),
        ),
    ]
