# Generated by Django 6.0.1 on 2026-01-21 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_change_sealing_to_metrology_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picturesstepentity",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="picturesstepentity",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="picturesstepentity",
            name="operator",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PhotoViewEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "pictures_step_id",
                    models.ForeignKey(
                        db_column="pictures_step_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_views",
                        to="app.picturesstepentity",
                    ),
                ),
            ],
            options={
                "db_table": "PHOTO_VIEW",
            },
        ),
    ]
