# Generated by Django 6.0.1 on 2026-01-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_fa_add_fsec_step_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="airtightnesstestlpstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="airtightnesstestlpstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="depressurizationstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="depressurizationstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="gasfillingbpstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="gasfillingbpstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="gasfillinghpstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="gasfillinghpstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="permeationstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="permeationstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="repressurizationstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="repressurizationstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="faentity",
            name="fsec_version_id",
            field=models.OneToOneField(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fa",
                to="app.fsecentity",
            ),
        ),
        migrations.AddIndex(
            model_name="airtightnesstestlpstepentity",
            index=models.Index(fields=["fsec_version_id"], name="airtight_lp_fsec_idx"),
        ),
        migrations.AddIndex(
            model_name="depressurizationstepentity",
            index=models.Index(fields=["fsec_version_id"], name="depress_fsec_idx"),
        ),
        migrations.AddIndex(
            model_name="gasfillingbpstepentity",
            index=models.Index(fields=["fsec_version_id"], name="gas_fill_bp_fsec_idx"),
        ),
        migrations.AddIndex(
            model_name="gasfillinghpstepentity",
            index=models.Index(fields=["fsec_version_id"], name="gas_fill_hp_fsec_idx"),
        ),
        migrations.AddIndex(
            model_name="permeationstepentity",
            index=models.Index(fields=["fsec_version_id"], name="permeation_fsec_idx"),
        ),
        migrations.AddIndex(
            model_name="repressurizationstepentity",
            index=models.Index(fields=["fsec_version_id"], name="repress_fsec_idx"),
        ),
    ]
