# Generated by Django 6.0.1 on 2026-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_airtightnesstestlpstepentity_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaignentity",
            index=models.Index(fields=["year"], name="campaign_year_idx"),
        ),
        migrations.AddIndex(
            model_name="fsecentity",
            index=models.Index(fields=["fsec_uuid"], name="fsec_fsec_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="fsecentity",
            index=models.Index(fields=["is_active"], name="fsec_is_active_idx"),
        ),
    ]
