# Generated by Django 5.1.4 on 2026-02-26 11:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_campaignentity_campaign_year_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningMemberPeriodEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_name", models.CharField(max_length=100)),
                ("member_role", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("week_num", models.IntegerField()),
                ("period_type", models.CharField(max_length=20)),
                (
                    "commentaire",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "PLANNING_MEMBER_PERIOD",
                "unique_together": {("member_name", "year", "week_num")},
            },
        ),
        migrations.CreateModel(
            name="PlanningWeekStateEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                ("week_num", models.IntegerField()),
                ("state", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "PLANNING_WEEK_STATE",
                "unique_together": {("year", "week_num")},
            },
        ),
        migrations.CreateModel(
            name="PlanningCellAnnotationEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_label", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("week_num", models.IntegerField()),
                ("text", models.TextField(max_length=1000)),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="campaign_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_annotations",
                        to="app.campaignentity",
                    ),
                ),
            ],
            options={
                "db_table": "PLANNING_CELL_ANNOTATION",
                "unique_together": {("campaign", "step_label", "year", "week_num")},
            },
        ),
        migrations.CreateModel(
            name="PlanningFsecCellLinkEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_label", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("week_num", models.IntegerField()),
                ("fsec_uuid", models.UUIDField()),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="campaign_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_fsec_links",
                        to="app.campaignentity",
                    ),
                ),
            ],
            options={
                "db_table": "PLANNING_FSEC_CELL_LINK",
                "unique_together": {("campaign", "step_label", "year", "week_num", "fsec_uuid")},
            },
        ),
    ]
