# Generated by Django 5.1.4 on 2026-02-26 14:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_planning_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabMachineEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "PLANNING_LAB_MACHINE",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabSalleEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "PLANNING_LAB_SALLE",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabEventEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "machine",
                    models.ForeignKey(
                        db_column="machine_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.labmachineentity",
                    ),
                ),
            ],
            options={
                "db_table": "PLANNING_LAB_EVENT",
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="labmachineentity",
            name="salle",
            field=models.ForeignKey(
                db_column="salle_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.labsalleentity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labmachineentity",
            unique_together={("salle", "name")},
        ),
    ]
