# Generated by Django 5.1.4 on 2026-02-26 16:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_member_period_date_based"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningCampaignStepEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_uuid", models.UUIDField()),
                ("step_label", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "PLANNING_CAMPAIGN_STEP",
                "ordering": ["start_date"],
                "unique_together": {("campaign_uuid", "step_label")},
            },
        ),
    ]
