# Generated by Django 5.1.4 on 2026-02-26 16:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_planningcampaignstepentity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planningcampaignstepentity",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="planningcampaignstepentity",
            name="fsec_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name="planningcampaignstepentity",
            unique_together={("campaign_uuid", "step_label", "fsec_uuid")},
        ),
    ]
