# Generated by Django 5.1.4 on 2026-02-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_planningcampaignstepentity_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevententity",
            name="category",
            field=models.CharField(
                choices=[
                    ("Maintenance", "Maintenance"),
                    ("Panne", "Panne"),
                    ("Installation", "Installation"),
                    ("Calibration", "Calibration"),
                    ("Nettoyage", "Nettoyage"),
                    ("Autre", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planningcampaignstepentity",
            name="fsec_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="planningcampaignstepentity",
            name="step_label",
            field=models.CharField(
                choices=[
                    ("Assemblage", "Assemblage"),
                    ("Métrologie", "Métrologie"),
                    ("Livraison", "Livraison"),
                    ("Tir", "Tir"),
                    ("Réception cibles", "Réception cibles"),
                    ("Gaz", "Gaz"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planningmemberperiodentity",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("congés", "congés"),
                    ("mission", "mission"),
                    ("formation", "formation"),
                    ("rtt", "rtt"),
                    ("maladie", "maladie"),
                    ("télétravail", "télétravail"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planningweekstateentity",
            name="state",
            field=models.CharField(
                choices=[("vacances", "vacances"), ("fermeture", "fermeture")],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="labevententity",
            index=models.Index(
                fields=["start_date"], name="PLANNING_LA_start_d_8b13bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labevententity",
            index=models.Index(
                fields=["machine_id"], name="PLANNING_LA_machine_1ea28f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningcampaignstepentity",
            index=models.Index(fields=["year"], name="PLANNING_CA_year_f31822_idx"),
        ),
        migrations.AddIndex(
            model_name="planningcampaignstepentity",
            index=models.Index(
                fields=["campaign_uuid"], name="PLANNING_CA_campaig_da17a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningcellannotationentity",
            index=models.Index(fields=["year"], name="PLANNING_CE_year_4307ff_idx"),
        ),
        migrations.AddIndex(
            model_name="planningfseccelllinkentity",
            index=models.Index(fields=["year"], name="PLANNING_FS_year_b8cce1_idx"),
        ),
        migrations.AddIndex(
            model_name="planningmemberperiodentity",
            index=models.Index(fields=["year"], name="PLANNING_ME_year_d57331_idx"),
        ),
        migrations.AddIndex(
            model_name="planningweekstateentity",
            index=models.Index(fields=["year"], name="PLANNING_WE_year_350c16_idx"),
        ),
    ]
