# Generated by Django 5.1.4 on 2026-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_planning_audit_trail"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="planningcampaignstepentity",
            new_name="PLANNING_CA_campaig_da17a4_idx",
            old_name="idx_campaign_step_campaign",
        ),
        migrations.RenameIndex(
            model_name="planningmemberperiodentity",
            new_name="PLANNING_ME_start_d_e70c1e_idx",
            old_name="idx_member_period_dates",
        ),
        migrations.AlterField(
            model_name="planningcellannotationentity",
            name="step_label",
            field=models.CharField(
                choices=[
                    ("Assemblage", "Assemblage"),
                    ("Métrologie", "Métrologie"),
                    ("Livraison", "Livraison"),
                    ("Tir", "Tir"),
                    ("Réception cibles", "Réception cibles"),
                    ("Gaz", "Gaz"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planningfseccelllinkentity",
            name="step_label",
            field=models.CharField(
                choices=[
                    ("Assemblage", "Assemblage"),
                    ("Métrologie", "Métrologie"),
                    ("Livraison", "Livraison"),
                    ("Tir", "Tir"),
                    ("Réception cibles", "Réception cibles"),
                    ("Gaz", "Gaz"),
                ],
                max_length=50,
            ),
        ),
    ]
