# Generated by Django 5.1.4 on 2026-03-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_fsec_composite_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fsecentity",
            name="idx_fsec_campaign_active",
        ),
    ]
