# Generated by Django 5.1.4 on 2026-03-02 19:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_remove_fsecentity_idx_fsec_campaign_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbaseEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("jet_de_gaz", "Jet de Gaz"),
                            ("hp", "HP"),
                            ("bp", "BP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "soufflet_v1",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("capteur_v1", models.CharField(blank=True, default="", max_length=50)),
                (
                    "offset_v1_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mesurande_lie_v1_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sensibilite_v1_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "signal_meteociel_v1_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "capteur_cible_pfeiffer_mbar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("etendue_v1_mbar", models.IntegerField(blank=True, null=True)),
                (
                    "test_etancheite_he",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "test_capteur_mrg",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("etalonnage_date", models.DateField(blank=True, null=True)),
                ("observations_v1", models.TextField(blank=True, default="")),
                ("operationnelle_aimant", models.BooleanField(default=False)),
                ("operationnelle_broche", models.BooleanField(default=False)),
                (
                    "localisation_actuelle",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "cote_ve",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "decalage_angulaire",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "chargement_mcc",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "soufflet_v2",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("capteur_v2", models.CharField(blank=True, default="", max_length=50)),
                (
                    "offset_v2_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sensibilite_v2_mv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("etendue_v2_mbar", models.IntegerField(blank=True, null=True)),
                ("observations_v2", models.TextField(blank=True, default="")),
                ("electrovanne", models.BooleanField(default=False)),
                ("fsec_history", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "EMBASE",
                "ordering": ["identifier"],
            },
        ),
    ]
