# Generated by Django 5.1.4 on 2026-03-05 18:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_embaseentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtalonnageEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offset_0_bar_mv",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "mesurande_0_bar_lie",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "signal_etendue_mv",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "signal_pa_meteociel",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("operateur", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embase",
                    models.ForeignKey(
                        db_column="embase_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etalonnages",
                        to="app.embaseentity",
                    ),
                ),
            ],
            options={
                "db_table": "ETALONNAGE",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
