# Generated by Django 5.1.4 on 2026-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_etalonnageentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="embaseentity",
            name="capteur_cible_pfeiffer_v2_mbar",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="embaseentity",
            name="mesurande_lie_v2_mv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="embaseentity",
            name="signal_meteociel_v2_mv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="embaseentity",
            name="test_capteur_mrg_v2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="embaseentity",
            name="test_etancheite_he_v2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
