# Generated by Django 5.1.4 on 2026-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_embaseentity_capteur_cible_pfeiffer_v2_mbar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embaseentity",
            name="nombre_voies",
            field=models.IntegerField(choices=[(1, "1 voie"), (2, "2 voies")], default=1),
        ),
    ]
