# Generated by Django 5.1.4 on 2026-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_embase_nombre_voies"),
    ]

    operations = [
        migrations.AddField(
            model_name="etalonnageentity",
            name="voie",
            field=models.IntegerField(choices=[(1, "V1"), (2, "V2")], default=1),
        ),
    ]
