# Generated by Django 5.1.4 on 2026-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_etalonnageentity_voie"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="etalonnageentity",
            constraint=models.UniqueConstraint(
                fields=("embase", "voie", "date"), name="uq_etalonnage_embase_voie_date"
            ),
        ),
    ]
