# Generated by Django 5.1.4 on 2026-03-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_etalonnageentity_uq_etalonnage_embase_voie_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasfillinghpstepentity",
            name="embase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gas_filling_hp_steps_embase",
                to="app.embaseentity",
            ),
        ),
    ]
