# Generated by Django 5.1.4 on 2026-03-10 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_gasfillinghpstepentity_embase"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="labevententity",
            new_name="lab_event_start_date_idx",
            old_name="PLANNING_LA_start_d_8b13bd_idx",
        ),
        migrations.RenameIndex(
            model_name="labevententity",
            new_name="lab_event_machine_id_idx",
            old_name="PLANNING_LA_machine_1ea28f_idx",
        ),
        migrations.RenameIndex(
            model_name="planningcampaignstepentity",
            new_name="pln_campstep_year_idx",
            old_name="PLANNING_CA_year_f31822_idx",
        ),
        migrations.RenameIndex(
            model_name="planningcampaignstepentity",
            new_name="pln_campstep_camp_idx",
            old_name="PLANNING_CA_campaig_da17a4_idx",
        ),
        migrations.RenameIndex(
            model_name="planningcellannotationentity",
            new_name="pln_cellannot_year_idx",
            old_name="PLANNING_CE_year_4307ff_idx",
        ),
        migrations.RenameIndex(
            model_name="planningfseccelllinkentity",
            new_name="pln_fseclink_year_idx",
            old_name="PLANNING_FS_year_b8cce1_idx",
        ),
        migrations.RenameIndex(
            model_name="planningmemberperiodentity",
            new_name="pln_memperiod_year_idx",
            old_name="PLANNING_ME_year_d57331_idx",
        ),
        migrations.RenameIndex(
            model_name="planningmemberperiodentity",
            new_name="pln_memperiod_dates_idx",
            old_name="PLANNING_ME_start_d_e70c1e_idx",
        ),
        migrations.RenameIndex(
            model_name="planningweekstateentity",
            new_name="planning_week_state_year_idx",
            old_name="PLANNING_WE_year_350c16_idx",
        ),
        migrations.AddField(
            model_name="assemblystepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="assemblystepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="assemblystepentity",
            name="operator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaignentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="metrologystepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="metrologystepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="metrologystepentity",
            name="operator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="picturesstepentity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="picturesstepentity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="airtightnesstestlpstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="airtightness_test_lp_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="assemblybenchentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="assemblystepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assembly_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="campaigndocumentsubtypesentity",
            name="type_id",
            field=models.ForeignKey(
                db_column="type_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subtypes",
                to="app.campaigndocumenttypesentity",
            ),
        ),
        migrations.AlterField(
            model_name="campaigndocumenttypesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="campaignfiletypesentity",
            name="subtype_id",
            field=models.ForeignKey(
                db_column="subtype_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_types",
                to="app.campaigndocumentsubtypesentity",
            ),
        ),
        migrations.AlterField(
            model_name="campaigninstallationsentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="campaignrolesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="campaignstatusentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="campaigntypesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="depressurizationstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="depressurization_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="facriticalityentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="faentity",
            name="fsec_version_id",
            field=models.OneToOneField(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fa",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="fastatusentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fatypeentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fseccategoryentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fsecdocumentsubtypesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fsecdocumentsubtypesentity",
            name="type_id",
            field=models.ForeignKey(
                db_column="type_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subtypes",
                to="app.fsecdocumenttypesentity",
            ),
        ),
        migrations.AlterField(
            model_name="fsecdocumenttypesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fsecentity",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                db_column="campaign_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fsecs",
                to="app.campaignentity",
            ),
        ),
        migrations.AlterField(
            model_name="fsecrackentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fsecrolesentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fsecstatusentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="gasfillingbpstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gas_filling_bp_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="gasfillinghpstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gas_filling_hp_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="metrologymachineentity",
            name="label",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="metrologystepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metrology_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="permeationstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permeation_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="picturesstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pictures_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="picturesstepentity",
            name="operator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="planningcampaignstepentity",
            name="fsec_uuid",
            field=models.ForeignKey(
                db_column="fsec_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_campaign_steps",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="planningfseccelllinkentity",
            name="fsec_uuid",
            field=models.ForeignKey(
                db_column="fsec_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_fsec_links",
                to="app.fsecentity",
            ),
        ),
        migrations.AlterField(
            model_name="repressurizationstepentity",
            name="fsec_version_id",
            field=models.ForeignKey(
                db_column="fsec_version_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repressurization_steps",
                to="app.fsecentity",
            ),
        ),
    ]
