# Generated by Django 5.1.4 on 2026-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_airtightnesstestlpstepentity_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignentity",
            name="semester",
            field=models.CharField(choices=[("S1", "S1"), ("S2", "S2")], max_length=2),
        ),
    ]
