# Generated by Django 5.1.4 on 2026-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_userprofileentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileentity",
            name="laboratoire",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofileentity",
            name="service",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
