# Generated by Django 5.1.4 on 2026-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_userprofileentity_laboratoire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileentity",
            name="bureau",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofileentity",
            name="numero",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
