# Generated by Django 5.1.4 on 2026-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_userprofileentity_bureau_userprofileentity_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="faentity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
