# Generated by Django 5.1.4 on 2026-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_faentity_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileentity",
            name="dashboard_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
