# Generated by Django 5.1.15 on 2026-04-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_backfill_steps_user_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="faentity",
            name="closure_validator_user",
            field=models.ForeignKey(
                blank=True,
                db_column="closure_validator_user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="faentity",
            name="discoverer_user",
            field=models.ForeignKey(
                blank=True,
                db_column="discoverer_user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="faentity",
            name="iec_validation_open_user",
            field=models.ForeignKey(
                blank=True,
                db_column="iec_validation_open_user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="faentity",
            name="iec_validation_progress_user",
            field=models.ForeignKey(
                blank=True,
                db_column="iec_validation_progress_user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
    ]
