# Generated by Django 5.1.15 on 2026-04-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_backfill_fa_user_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="etalonnageentity",
            name="operateur_user",
            field=models.ForeignKey(
                blank=True,
                db_column="operateur_user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
    ]
