# Generated by Django 5.1.15 on 2026-04-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_backfill_etalonnage_user_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignteamsentity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="fsecteamsentity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="app.userprofileentity",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="campaignteamsentity",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fsecteamsentity",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
