# Generated by Django 5.1.15 on 2026-04-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_backfill_teams_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblystepentity',
            name='hydrometric_temperature',
        ),
    ]
