# Generated by Django 5.1.15 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def clear_lab_events(apps, schema_editor):
    """Purge les événements labo : leur machine_id référençait des LabMachine
    désormais supprimées (non mappables vers le parc Matériel)."""
    LabEventEntity = apps.get_model("app", "LabEventEntity")
    LabEventEntity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_step_machines_m2m'),
    ]

    operations = [
        migrations.RunPython(clear_lab_events, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='labmachineentity',
            name='salle',
        ),
        migrations.AlterField(
            model_name='labevententity',
            name='machine',
            field=models.ForeignKey(
                db_column='machine_id',
                on_delete=django.db.models.deletion.CASCADE,
                to='app.machineentity',
            ),
        ),
        migrations.DeleteModel(
            name='LabSalleEntity',
        ),
        migrations.DeleteModel(
            name='LabMachineEntity',
        ),
    ]
