# Generated by Django 5.1.15 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def clear_lab_events(apps, schema_editor):
    """Purge les événements labo : leur machine_id référençait des LabMachine
    désormais supprimées (non mappables vers le parc Matériel)."""
    LabEventEntity = apps.get_model("app", "LabEventEntity")
    LabEventEntity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_step_machines_m2m"),
    ]

    operations = [
        migrations.RunPython(clear_lab_events, migrations.RunPython.noop),
        # Repointe LabEvent vers le parc Matériel : LabMachineEntity n'a plus
        # de FK entrante.
        migrations.AlterField(
            model_name="labevententity",
            name="machine",
            field=models.ForeignKey(
                db_column="machine_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.machineentity",
            ),
        ),
        # Supprimer LabMachine d'abord : sa FK `salle` vers LabSalle disparaît
        # avec la table. Évite un RemoveField(salle) incompatible SQLite
        # (reconstruction de table + contrainte sur la colonne supprimée).
        migrations.DeleteModel(
            name="LabMachineEntity",
        ),
        migrations.DeleteModel(
            name="LabSalleEntity",
        ),
    ]
