# Generated by Django 5.1.15 on 2026-05-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_backfill_steps_multi_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faentity',
            name='fsec_version_id',
            field=models.ForeignKey(db_column='fsec_version_id', on_delete=django.db.models.deletion.PROTECT, related_name='fas', to='app.fsecentity'),
        ),
    ]
