# Generated by Django 5.1.15 on 2026-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_alter_faentity_fsec_version_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileentity",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="users/avatars/"
            ),
        ),
    ]
