# Generated by Django 5.1.15 on 2026-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsecentity",
            name="delivery_acceptor_signature",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="fsec/signatures/"
            ),
        ),
        migrations.AddField(
            model_name="fsecentity",
            name="delivery_validator_signature",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="fsec/signatures/"
            ),
        ),
        migrations.AddField(
            model_name="userprofileentity",
            name="signature",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="users/signatures/"
            ),
        ),
    ]
