# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_fsecentity_delivery_acceptor_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsecentity",
            name="assembly_plan_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="fsec/assembly-plan/"
            ),
        ),
        migrations.AddField(
            model_name="fsecentity",
            name="assembly_plan_annotations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
